# Generated by Django 5.1.4 on 2024-12-13 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competiciones', '0001_initial'),
        ('selecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('presupuesto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fundacion', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('competencias', models.ManyToManyField(related_name='equipos', to='competiciones.competencia')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='selecciones.nacionalidad')),
                ('patrocinador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='equipos.patrocinador')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('experiencia', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Ofensivo', 'Ofensivo'), ('Defensivo', 'Defensivo'), ('Equilibrado', 'Equilibrado')], max_length=50)),
                ('entrenamiento', models.IntegerField(default=0)),
                ('tactica', models.IntegerField(default=0)),
                ('motivacion', models.IntegerField(default=0)),
                ('equipo_actual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenador', to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadio', to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('habilidades', models.JSONField()),
                ('moral', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lesion', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='equipos.equipo')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='selecciones.nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('impacto', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesiones', to='equipos.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='competiciones.competencia')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='equipos.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='equipos.equipo')),
                ('estadio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='equipos.estadio')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='equipos.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaPorTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('partidos', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='equipos.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='equipos.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='equipos.temporada')),
            ],
            options={
                'unique_together': {('jugador', 'temporada', 'equipo')},
            },
        ),
    ]
