# Generated by Django 5.1.4 on 2024-12-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='asistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_contra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_favor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='asistencias_carrera',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='goles_carrera',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='partidos_carrera',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='asistencias_jugadores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_jugadores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='estadisticaportemporada',
            index=models.Index(fields=['jugador', 'temporada', 'equipo'], name='equipos_est_jugador_ac2ab4_idx'),
        ),
    ]
