# Generated by Django 5.1.4 on 2025-01-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_asistencias_equipo_goles_contra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='asistencias_jugadores',
            new_name='asistencias_jugadores_local',
        ),
        migrations.RenameField(
            model_name='partido',
            old_name='goles_jugadores',
            new_name='asistencias_jugadores_visitante',
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_jugadores_local',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_jugadores_visitante',
            field=models.JSONField(default=dict),
        ),
    ]
