# Generated by Django 5.1.4 on 2025-01-15 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_rename_asistencias_jugadores_partido_asistencias_jugadores_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrocinador',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='estadio',
            name='mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='asistencias_internacionales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='forma_fisica',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='jugador',
            name='goles_internacionales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='partidos_internacionales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='clima',
            field=models.CharField(choices=[('Despejado', 'Despejado'), ('Parcialmente nublado', 'Parcialmente nublado'), ('Nublado', 'Nublado'), ('Lluvia', 'Lluvia')], default='Despejado', max_length=20),
        ),
        migrations.AddField(
            model_name='partido',
            name='espectadores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='objetivo_basico',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='objetivo_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='moral',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_transferencia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_transferencia', models.DateField()),
                ('equipo_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='equipos.equipo')),
                ('equipo_nuevo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichajes', to='equipos.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='equipos.jugador')),
            ],
        ),
    ]
