# Generated by Django 5.1.4 on 2025-01-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_remove_patrocinador_presupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='portero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='presupuesto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='salario',
            field=models.IntegerField(default=60000),
        ),
    ]
