# Generated by Django 5.1.4 on 2025-02-14 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_jugador_portero_alter_equipo_presupuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo_pases', models.CharField(choices=[('C', 'Cortos'), ('L', 'Largos'), ('M', 'Mixtos')], default='M', max_length=1)),
                ('actitud', models.CharField(choices=[('A', 'Ataque'), ('D', 'Defensa'), ('E', 'Equilibrado'), ('L', 'Lateral')], default='E', max_length=1)),
                ('entradas', models.CharField(choices=[('F', 'Fuertes'), ('N', 'Normal'), ('S', 'Suaves')], default='N', max_length=1)),
                ('marcaje', models.CharField(choices=[('F', 'Férreo'), ('N', 'Normal'), ('Z', 'A zona')], default='N', max_length=1)),
                ('presion', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='M', max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('titulares', models.JSONField(default=list)),
                ('suplentes', models.JSONField(default=list)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='equipos.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='equipos.partido')),
            ],
        ),
    ]
