# Generated by Django 5.1.4 on 2025-04-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_alineacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alineacion',
            name='suplentes',
        ),
        migrations.RemoveField(
            model_name='alineacion',
            name='titulares',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='asistencias_jugadores_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='asistencias_jugadores_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='goles_jugadores_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='goles_jugadores_visitante',
        ),
        migrations.AddField(
            model_name='estadisticaportemporada',
            name='goles_de_falta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaportemporada',
            name='goles_de_penal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaportemporada',
            name='goles_encajados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaportemporada',
            name='minutos_jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaportemporada',
            name='tarjetas_amarillas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaportemporada',
            name='tarjetas_rojas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='atajadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='defensa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='desmarques',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='distribucion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='lateral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='mentalidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='pases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='remate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='vision',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GolPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('es_local', models.BooleanField()),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('Penal', 'Penal'), ('Falta', 'Falta'), ('Autogol', 'Autogol')], default='Normal', max_length=20)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='equipos.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='equipos.partido')),
            ],
            options={
                'ordering': ['minuto'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_local', models.BooleanField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='equipos.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='equipos.partido')),
                ('gol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='equipos.golpartido')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('es_local', models.BooleanField()),
                ('es_amarilla', models.BooleanField()),
                ('tipo', models.CharField(choices=[('Amarilla', 'Amarilla'), ('Roja', 'Roja')], default='Amarilla', max_length=20)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='equipos.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='equipos.partido')),
            ],
            options={
                'ordering': ['minuto'],
            },
        ),
        migrations.CreateModel(
            name='JugadorAlineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DFC', 'Defensa Central'), ('DFD', 'Defensa Derecho'), ('DFI', 'Defensa Izquierdo'), ('MCD', 'Mediocentro defensivo'), ('MED', 'Mediocampista Derecho'), ('MEI', 'Mediocampista Izquierdo'), ('MEC', 'Mediocampista central'), ('MPC', 'Mediapunta Centro'), ('MPD', 'Mediapunta Derecho'), ('MPI', 'Mediapunta Izquierdo'), ('DLC', 'Delantero Centro'), ('DLD', 'Delantero Derecho'), ('DLI', 'Delantero Izquierdo')], max_length=3)),
                ('es_titular', models.BooleanField(default=True)),
                ('numero_suplente', models.IntegerField(blank=True, null=True)),
                ('alineacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_alineacion', to='equipos.alineacion')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='equipos.jugador')),
            ],
            options={
                'ordering': ['numero_suplente'],
                'constraints': [models.CheckConstraint(condition=models.Q(('es_titular', False), ('numero_suplente__isnull', True), _connector='OR'), name='titular_no_numero_suplente')],
                'unique_together': {('alineacion', 'jugador')},
            },
        ),
    ]
