# Generated by Django 5.1.4 on 2024-12-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Liga Local', 'Liga Local'), ('Copa Local', 'Copa Local'), ('Copa Internacional', 'Copa Internacional'), ('Seleccion Nacional', 'Seleccion Nacional'), ('Amistosos', 'Amistosos'), ('Copa Internacional de Equipos', 'Copa Internacional de Equipos'), ('Partidos de Promocion', 'Partidos de Promocion')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
    ]
