# Generated by Django 5.1.4 on 2024-12-18 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competiciones', '0001_initial'),
        ('equipos', '0001_initial'),
        ('selecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='equipos',
            field=models.ManyToManyField(to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='nacionalidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='selecciones.nacionalidad'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.temporada'),
        ),
    ]
