# Generated by Django 5.1.4 on 2024-12-13 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competiciones', '0001_initial'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='equipos.temporada'),
        ),
    ]
